version: '3.3'

services:
  php-httpd:
    build:
      context: ./.docker/apache
      dockerfile: Dockerfile
    container_name: pdf_php_apache
    volumes:
      - .:/var/www/html/
    environment:
      DATABASE_URL: mysql://root:root_pass@mysql:3306/sunfinance
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    container_name: pdf_mysql
    image: mysql:8
    restart: always
    command: [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      TZ: "Europe/Riga"
      MYSQL_ROOT_PASSWORD: "root_pass"

  phpmyadmin:
    container_name: pdf_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
    ports:
      - 8081:81
    links:
      - mysql
    depends_on:
      - php-httpd